name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/general.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          base_indepth: true
          base_hireable: no
          base_skip: archived
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_limit: 15
          extras_css: |
            .field svg {
              fill: #05D9E8;
            }
            .field {
              color: #05D9E8;
            }
            h1, h2, h3 {
              color: #FF2A6D !important;
            }
          extras_js: |
            for (const {a, b} of [
              {a:"#216e39", b:"#00FF9F"},
              {a:"#30a14e", b:"#05D9E8"},
              {a:"#40c463", b:"#FF2A6D"},
              {a:"#9be9a8", b:"#FFC100"},
              {a:"#ebedf0", b:"#1a1a2e"},
            ])
            document.querySelectorAll(`svg g [fill="${a}"]`).forEach(node => node.setAttribute("fill", b))

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage, bytes-size, lines
          extras_css: |
            .field svg {
              fill: #05D9E8;
            }
            .field {
              color: #05D9E8;
            }
            h1, h2, h3 {
              color: #FF2A6D !important;
            }

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          extras_css: |
            .field svg {
              fill: #05D9E8;
            }
            .field {
              color: #05D9E8;
            }
            h1, h2, h3 {
              color: #FF2A6D !important;
            }
